DROP DATABASE IF EXISTS jeans_rest;
CREATE DATABASE jeans_rest;

\c jeans_rest;

CREATE TABLE menjeans (
    id SERIAL PRIMARY KEY,
    nameru VARCHAR NOT NULL,
    nameeng VARCHAR NOT NULL,
    discription VARCHAR NOT NULL,
    urls VARCHAR NOT NULL
);

INSERT INTO menjeans(nameru, nameeng, discription, urls) VALUES ('Джинсы с высокой посадкой', 'Hight rise jeans', 'Верх пояса джинсов на уровне или выше пупка. Расстояние от пояса до шагового шва 25 см и более. У многих брендов нет мужских джинсов с высокой посадкой. В настоящее время редкий вариант.', 'https://images.asos-media.com/products/sinie-vintazhnye-dzhinsy-s-zavyshennoj-taliej-asos-design/10839108-1-midwashvintage?$n_1920w$&wid=1926&fit=constrain');
INSERT INTO menjeans(nameru, nameeng, discription, urls) VALUES ('Джинсы с средней посадкой', 'Mid rise jeans', 'Верх пояса джинсов немного ниже пупка - примерно на 1-3 см. Расстояние от пояса до шагового шва от 20 до 24 см. Средняя посадка примерно соответствует уровню талии.', 'https://men-mag.com/wp-content/uploads/2023/03/mid-rise-balenciaga.png');
INSERT INTO menjeans(nameru, nameeng, discription, urls) VALUES ('Джинсы с низкой посадкой', 'Low rise jeans', 'Верх пояса джинсов примерно на 5 см ниже пупка. Расстояние от пояса до шагового шва до 20 см. Низкая посадка примерно чуть ниже уровня талии. Низкая посадка джинсов является самой распространенной. Часто называется просто below waist - "ниже талии".', 'https://men-mag.com/wp-content/uploads/2023/03/low-rise-boss.png');
INSERT INTO menjeans(nameru, nameeng, discription, urls) VALUES ('Джинсы с низким шаговым швом', 'Low crotch jeans', 'Верх пояса джинсов примерно на 5 см ниже пупка - как у низкой посадки, но шаговый шов значительно ниже стандартных джинсов.', 'https://men-mag.com/wp-content/uploads/2023/03/low-crotch-benetton.png');
INSERT INTO menjeans(nameru, nameeng, discription, urls) VALUES ('Джинсы клеш', 'Flared jeans, Bell bottom', 'Нижняя часть штанины значительно расширяется к низу. Если степень расширения штанины не значительная, то такие расклешенные джинсы у многих брендов считаются bootcut.', 'https://men-mag.com/wp-content/uploads/2023/03/flared-cut.png');
INSERT INTO menjeans(nameru, nameeng, discription, urls) VALUES ('Джинсы под ботинки', 'Bootcut jeans', 'Нижняя часть штанин джинсов от колена слегка расширяется к низу. Такие джинсы, даже с высокими и массивными ботинками, не будут их обтягивать.', 'https://men-mag.com/wp-content/uploads/2023/03/boot-cut.png');
INSERT INTO menjeans(nameru, nameeng, discription, urls) VALUES ('Джинсы с прямой штаниной', 'Straight cut jeans', 'Это джинсы с прямой штаниной от колена до нижнего края штаниныю', 'https://men-mag.com/wp-content/uploads/2023/03/straight-cut.png');
INSERT INTO menjeans(nameru, nameeng, discription, urls) VALUES ('Джинсы с полузауженной штаниной', 'Semi tappered leg jeans', 'Это достаточное условное выделение джинсов со штанинами некой средней зауженности. Сам tapered cut может быть с различной степенью сужения.', 'https://men-mag.com/wp-content/uploads/2023/03/semi-taperd-cut.png');
INSERT INTO menjeans(nameru, nameeng, discription, urls) VALUES ('Джинсы с зауженной штаниной', 'Tappered leg jeans', 'Джинсы с различной степенью сужения штанины от колена до низа. Насколько сильно заужена штанина книзу, зависит от бренда и модели.', 'https://men-mag.com/wp-content/uploads/2023/03/tapered-cut.png');
INSERT INTO menjeans(nameru, nameeng, discription, urls) VALUES ('Джинсы свободного кроя прямые', 'Loose fit jeans', 'Loose fit - это свободные джинсы. Могут быть прямыми - straight loose fit или сужающимися - tapered loose fit. У некоторых брендов называются Relaxed fit jeans.', 'https://men-mag.com/wp-content/uploads/2023/03/loose-fit-straight.png');
INSERT INTO menjeans(nameru, nameeng, discription, urls) VALUES ('Свободные джинсы, сужающиеся книзу', 'Loose fit tappered jeans', 'Джинсы свободного кроя, сужающиеся от самого верха книзу штанины.', 'https://men-mag.com/wp-content/uploads/2023/03/loose-fit-tapered.png');
INSERT INTO menjeans(nameru, nameeng, discription, urls) VALUES ('Прямые джинсы', 'Straight fit jeans', 'Прямые джинсы могут иметь разную степень прилегания - свободные прямые, классические прямые, узкие прямые и т.д.', 'https://men-mag.com/wp-content/uploads/2023/03/straight-fit.png');
INSERT INTO menjeans(nameru, nameeng, discription, urls) VALUES ('Сужающиеся книзу джинсы', 'Tappered fit jeans', 'Tapered fit jeans - джинсы с постепенным сужением к низу по всей штанине, повторяющие естественный силуэт. Могут быть и свободного кроя - Relaxed tapered fit, и прилегающего, например Slim tapered fit.', 'https://men-mag.com/wp-content/uploads/2023/03/tapered-fit.png');
INSERT INTO menjeans(nameru, nameeng, discription, urls) VALUES ('Узкие джинсы', 'Slim fit jeans', 'Джинсы слим фит - прилегают в области бедер. Могут быть прямыми - Straight slim fit, или сужающимися Tapered slim fit.', 'https://men-mag.com/wp-content/uploads/2023/03/slim-fit.png');
INSERT INTO menjeans(nameru, nameeng, discription, urls) VALUES ('Скинни джинсы', 'Skinny fit jeans', 'Скинни джинсы просто полностью облегают бедра и ноги. Это самый узкий крой джинсов.', 'https://men-mag.com/wp-content/uploads/2023/03/skinny-fit.png');

CREATE TABLE womenjeans (
    id SERIAL PRIMARY KEY,
    nameru VARCHAR NOT NULL,
    nameeng VARCHAR NOT NULL,
    discription VARCHAR NOT NULL,
    urls VARCHAR NOT NULL
);

INSERT INTO womenjeans(nameru, nameeng, discription, urls) VALUES ('Джинсы с высокой посадкой', 'Hight rise jeans', 'Чем выше, тем лучше? По крайней мере, если говорить о современных фасонах джинсов, то именно такое впечатление у вас может сложиться. Эта модель джинсов характеризуются высокой талией, иногда даже выше пупка. В настоящее время высокую талию часто подчеркивают броскими пуговицами или талия свободно собрана завязывающимся поясом. Строго говоря, высокая талия - это скорее деталь кроя, чем самостоятельный фасон, потому что высокий пояс можно встретить как на зауженных и узких, так и на прямых или широких джинсах.', 'https://static.insales-cdn.com/files/1/1322/29844778/original/High_Waist_женские_джинсы_5-1687637452940.jpg');
INSERT INTO womenjeans(nameru, nameeng, discription, urls) VALUES ('Широкие Джинсы', 'Wide Leg Jeans', 'Широкие джинсы отличаются прямым и свободным кроем от бедра и до низа, обеспечивая максимальный комфорт и свободу движений. Этот стиль может варьироваться от слегка расширенных моделей до очень широких, создавая динамичный и современный силуэт. Широкие джинсы часто имеют высокую или среднюю посадку, что помогает визуально удлинить ноги и сделать фигуру более стройной.', 'https://static.insales-cdn.com/files/1/1254/29844710/original/Wide_Leg_женские_джинсы_13-1687637132002.jpg');
INSERT INTO womenjeans(nameru, nameeng, discription, urls) VALUES ('Джинсы клеш', 'Bootcut jeans', 'Относится ли bootcut к тем временам, когда синие джинсы носили в основном суровые ковбои? Мы не знаем наверняка, но под слегка расклешенными джинсами определенно найдется место для пары ковбойских сапог. Но даже если вы не проводите большую часть своей жизни верхом на лошади, объезжая стада скота, джинсы bootcut всегда будут хорошим выбором для нестареющего джинсового наряда. Посадка bootcut узкая на бедрах и немного расширяется от колена. Это, безусловно, делает их удобными. Джинсы Bootcut - это классика, и, как и все широкие фасоны, в настоящее время они переживают возвращение в моду.', 'https://static.insales-cdn.com/files/1/1227/29844683/original/mceu_23244676141687637013993-1687637014011.jpg');
INSERT INTO womenjeans(nameru, nameeng, discription, urls) VALUES ('Джинсы с прямой штаниной', 'Straight cut jeans', 'Вам нужен вечный фасон джинсов, который можно носить по любому поводу? Тогда мы хотели бы порекомендовать вам прямой крой. Эта классика имеет прямую штанину, свободную до самого низа. Не слишком узкие, не слишком широкие, а просто красивые и подходящие для любого стиля. Если вы хотите немного нарушить классический вид этого фасона, в наступающем сезоне выбирайте "обрезанную" версию. Здесь джинсы заканчиваются чуть выше щиколотки. Это выглядит современно и по-летнему.', 'https://static.insales-cdn.com/files/1/1198/29844654/original/Straight_Fit_женские_джинсы_11-1687636868911.jpg');
INSERT INTO womenjeans(nameru, nameeng, discription, urls) VALUES ('Джинсы Mom Fit', 'Mom Fit', 'Название mom fit («мамины джинсы») эта модель, по одной версии, получила за сходство с кроем, популярным у домохозяек в 1980-х и 1990-х годах. Это были прямые джинсы с высокой талией, которые отличались комфортом и практичностью. Современные момы вышли за рамки ассоциации с мамами и стали модными для всех возрастов. Их универсальный фасон — облегающий высокий верх и свободные штанины, чуть зауженные к щиколотке.', 'https://avatars.dzeninfra.ru/get-zen_doc/271828/pub_661e60983653ec51c029867e_661e60b53653ec51c0298bdf/scale_1200');
INSERT INTO womenjeans(nameru, nameeng, discription, urls) VALUES ('Джинсы-бойфренды', 'Boyfriend', 'Благодаря различным вариантам покроя джинсов-бойфрендов, этот фасон подходит любой фигуре. Если у вас узкая талия, но широкие бедра, выбирайте особенно свободные, повседневные фасоны. Если у вас узкие бедра, мы рекомендуем вам немного более узкий фасон, который не позволит утонуть в них. Когда дело доходит до стиля, у вас есть почти полная свобода действий. Кроссовки и крутые спортивные топы или даже женственные блузки отлично сочетаются с джинсами-бойфрендами. Свободный крой можно использовать даже для офиса с классическим блейзером, блузкой и женственными аксессуарами. В этом случае, однако, следует выбирать неяркие цвета.', 'https://static.insales-cdn.com/files/1/1285/29844741/original/mceu_39995217161687637280127-1687637280192.jpg');
INSERT INTO womenjeans(nameru, nameeng, discription, urls) VALUES ('Узкие джинсы', 'Slim Fit jeans', 'Джинсы slim fit, что можно перевести как стройный силуэт, относятся к моделям узкого кроя. Как и скинии, они плотно облегают талию, бедра и колени, но на щиколотках свободные и прямые. Слимы немного свободнее, чем скинни. На выбор есть разные вариации: с высокой или средней посадкой, немного укороченные или в полную длину.', 'https://avatars.dzeninfra.ru/get-zen_doc/271828/pub_661e60983653ec51c029867e_661e60b53653ec51c0298bde/scale_1200');
INSERT INTO womenjeans(nameru, nameeng, discription, urls) VALUES ('Скинни джинсы', 'Skinny Fit jeans', 'Джинсы-скинни - это очень женственный фасон, который подходит практически каждой женщине. Даже если у вас неидеальная фигура, пусть вас не отпугивает облегающий крой. Джинсы-скинни любимая вещь любого стилиста. Например, вы можете легко скрыть небольшие проблемные зоны с помощью широкой туники поверх брюк, не делая при этом силуэт бесформенным. Невысокие женщины также могут визуально удлинить ноги с помощью сочетания джинсов-скинни и туфель на высоком каблуке.', 'https://static.insales-cdn.com/files/1/1135/29844591/original/Skinny_Fit_женские_джинсы_7-1687636592113.jpg');
INSERT INTO womenjeans(nameru, nameeng, discription, urls) VALUES ('Джеггинсы', 'Jeggings', 'Джеггинсы — это сочетание джинсов и леггинсов. Чаще всего их делают из мягкой и эластичной ткани. Первые модели джеггинсов, появившиеся в начале 2000-х годов, больше напоминали супертонкие брюки. У джеггинсов нет молнии или пуговиц, вместо этого в верхней части делается стилизация. Иногда к ним делают пояс', 'https://avatars.dzeninfra.ru/get-zen_doc/271828/pub_661e60983653ec51c029867e_661e60b53653ec51c0298be0/scale_1200');